#!/usr/bin/python3 
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
  
client_id = 'cf614c21c9514eacbf313f4fc0824b52'
client_secret = '14a6d270f63940ffaff641572e507917'

client_credentials_manager = SpotifyClientCredentials(client_id, client_secret)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

def getTrackIDs(user, playlist_id):
    ids = []
    playlist = sp.user_playlist(user, playlist_id)
    for item in playlist['tracks']['items']:
        track = item['track']
        ids.append(track['id'])
    return ids

#ids = getTrackIDs(Username,playlistURL) 
#my sample playlist below
ids = getTrackIDs('ooPb2O_bQJ-deWxt9dvy7Q', '0GHWgHTiN2NpVO2uUqugYq')

def getTrackFeatures(id):
  meta = sp.track(id)
  features = sp.audio_features(id)

  # meta
  name = meta['name']
  album = meta['album']['name']
  artist = meta['album']['artists'][0]['name']
  release_date = meta['album']['release_date']
  track = [name, album, artist, release_date]
  return track

  # loop over track ids 
tracks = []
for i in range(5):
  track = getTrackFeatures(ids[i])
  tracks.append(track)

for i in tracks:     #Print Each Track as A List  
  print(i)


'''
This Script prints each track as a list in the order of name, album, artist, and release date. I can use the position operator to access a certain field of data. This is a simple version. I will develop a more complex version that displays more features of data that can be later used for analytical purposes to develop features for overall project. 
'''
